spring.application.name=try-out

# Koneksi Database
spring.datasource.url=jdbc:postgresql://localhost:5432/try_out
spring.datasource.username=postgres
spring.datasource.password=postgres
# Driver class name opsional di Spring Boot modern, tapi aman untuk tetap ada
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pengaturan JSONB (Sangat berguna untuk project bank/OBO kamu)
spring.jpa.properties.hibernate.type.json_format=jsonb

# Performance & Debugging
spring.threads.virtual.enabled=true
debug=false
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# Mematikan Security sementara jika kamu tidak ingin terganggu form login saat try-out
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration